CREATE TABLE PASSENGER
(PASSENGER_ID NUMBER PRIMARY KEY,
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20),
AGE NUMBER,
GENDER VARCHAR(1));

---------------------------------------

CREATE TABLE TICKET(
TICKET_NO NUMBER PRIMARY KEY,
FARE NUMBER NOT NULL);

----------------------------------------

CREATE TABLE TICKET_P(
TICKET_NO NUMBER,
PASSENGER_ID NUMBER,
CONSTRAINT TICKET_P_PK PRIMARY KEY(TICKET_NO , PASSENGER_ID));

-----------------------------------------

CREATE TABLE TICKET_B(
BUS_NO NUMBER,
TICKET_NO NUMBER,
DATE_B DATE,
BOARDING_CITY VARCHAR(20),
DROP_CITY VARCHAR(20),
START_J_TIME TIMESTAMP,
FINISH_J_TIME TIMESTAMP,
CONSTRAINT TICKET_B_PK PRIMARY KEY(BUS_NO , TICKET_NO));

------------------------------------------

CREATE TABLE BUS(
BUS_NO NUMBER PRIMARY KEY,
TYPE VARCHAR(10),
START_TIME DATE,
TOTAL_SEAT NUMBER,
RATE_PKM NUMBER);

------------------------------------------

CREATE TABLE BUS_C(
BUS_NO NUMBER,
CITY VARCHAR(20),
TIMEC DATE,
SEAT_AV NUMBER,
DISTANCE NUMBER,
CONSTRAINT BUS_C_PK PRIMARY KEY(BUS_NO , CITY));
