DECLARE 
C_PASSENGER_ID PASSENGER.PASSENGER_ID%TYPE;
C_FIRST_NAME PASSENGER.FIRST_NAME%TYPE;
C_LAST_NAME PASSENGER.LAST_NAME%TYPE;
C_AGE PASSENGER.AGE%TYPE;
C_GENDER PASSENGER.GENDER%TYPE;

CURSOR C_PASSENGER IS 
    SELECT PASSENGER_ID , FIRST_NAME , LAST_NAME , AGE , GENDER FROM PASSENGER;

BEGIN
    OPEN C_PASSENGER;
    LOOP
    FETCH C_PASSENGER INTO C_PASSENGER_ID , C_FIRST_NAME , C_LAST_NAME , C_AGE , C_GENDER;
        EXIT WHEN C_PASSENGER%NOTFOUND;
        IF (C_AGE > 18)
            THEN
            DBMS_OUTPUT.PUT_LINE(C_PASSENGER_ID || ' ' ||  C_FIRST_NAME|| ' ' || 
            C_LAST_NAME ||' ' || C_AGE ||' ' || C_GENDER);
        END IF;
    END LOOP;
    CLOSE C_PASSENGER;
END;
/
