INSERT INTO BUS
VALUES(5001 , 'AC' , CURRENT_TIMESTAMP , 45 , 6);

INSERT INTO BUS
VALUES(5002 , 'NON-AC' , CURRENT_TIMESTAMP , 40 , 8);

INSERT INTO BUS
VALUES(5003 , 'NON-AC' , CURRENT_TIMESTAMP , 50 , 5);

INSERT INTO BUS
VALUES(5004 , 'AC' , CURRENT_TIMESTAMP , 48 , 6);

INSERT INTO BUS
VALUES(5005 , 'AC' , CURRENT_TIMESTAMP , 45 , 7);

SELECT *
FROM BUS;
