INSERT INTO PASSENGER
VALUES(1 , 'JIGNESH' , 'JINJALA' , 19 , 'M');

INSERT INTO PASSENGER
VALUES(2 , 'JITENDRA' , 'JAT' , 20 , 'M');

INSERT INTO PASSENGER
VALUES(3 , 'DHARMIK' , 'JINJALA' , 16 , 'M');

INSERT INTO PASSENGER
VALUES(4 , 'ROHIT' , 'BAKOLIYA' , 19 , 'M');

INSERT INTO PASSENGER
VALUES(5 , 'ABHI' , 'LUNAGARIYA' , 18 , 'M');

SELECT * 
FROM PASSENGER
