CREATE OR REPLACE PROCEDURE FIND_PASSENGER(ID1 IN NUMBER)
IS
NAME1 VARCHAR(20);

BEGIN
SELECT FIRST_NAME INTO NAME1 FROM PASSENGER WHERE PASSENGER_ID = ID1;
DBMS_OUTPUT.PUT_LINE('THE PASSENGER NAME IS ' || NAME1 || ' WHOSE ID IS '|| ID1);
END;
/

BEGIN
FIND_PASSENGER(1);

END;
/
