CREATE OR REPLACE TRIGGER PRICE_CHANGE
AFTER DELETE OR INSERT OR UPDATE ON BUS
FOR EACH ROW

DECLARE
PRICE_CHANGE NUMBER;
BEGIN
PRICE_CHANGE := :OLD.RATE_PKM - :NEW.RATE_PKM;
DBMS_OUTPUT.PUT_LINE('OLD VALUE IS ' || :OLD.RATE_PKM || CHR(10) || 'NEW VALUE IS ' || :NEW.RATE_PKM);
DBMS_OUTPUT.PUT_LINE(PRICE_CHANGE);
END;
/

UPDATE BUS
SET RATE_PKM = RATE_PKM - 2
WHERE RATE_PKM > 2;

SELECT *
FROM BUS;
